 ─ python
      #!/usr/bin/env python3
      import os, sys, json, smtplib, ssl, pathlib, datetime, requests
      REPO_ROOT    = pathlib.Path(__file__).resolve().parent.parent
      PROMPT_FILE  = REPO_ROOT / "scripts" / "prompt.md"
      LEADS_DIR    = REPO_ROOT / "leads"
      TODAY        = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
      LEADS_FILE   = LEADS_DIR / f"{TODAY}.md"
      OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
      MODEL          = os.environ.get("OPENROUTER_MODEL", "openai/gpt-4o:online")
      GMAIL_SENDER    = os.environ["GMAIL_SENDER"]
      GMAIL_RECIPIENT = os.environ["GMAIL_RECIPIENT"]
      GMAIL_PASS      = os.environ["GMAIL_APP_PASSWORD"]
      def call_llm(prompt: str) -> str:
          api_key = os.environ["OPENROUTER_API_KEY"]
          r = requests.post(
              OPENROUTER_URL,
              headers={
                  "Authorization": f"Bearer {api_key}",
                  "Content-Type": "application/json",
                  "HTTP-Referer": "https://github.com/pawan-bapm/daily-pmpo-leads",
                  "X-Title": "Daily PM/PO Lead Sweep",
              },
              json={
                  "model": MODEL,
                  "messages": [
                      {"role": "system", "content": "You are a precise job-search research assistant. Follow the user's instructions
      exactly. Output ONLY the requested markdown tables - no preamble, no closing remarks, no JSON wrapper."},
                      {"role": "user", "content": prompt},
                  ],
                  "temperature": 0.2,
                  "max_tokens": 12000,
              },
              timeout=300,
          )
          r.raise_for_status()
          return r.json()["choices"][0]["message"]["content"]
      def send_email(subject: str, body: str) -> None:
          msg = f"From: {GMAIL_SENDER}\r\nTo: {GMAIL_RECIPIENT}\r\nSubject: {subject}\r\nContent-Type: text/plain;
      charset=utf-8\r\n\r\n{body}"
          ctx = ssl.create_default_context()
          with smtplib.SMTP("smtp.gmail.com", 587, timeout=60) as s:
              s.starttls(context=ctx)
              s.login(GMAIL_SENDER, GMAIL_PASS)
              s.sendmail(GMAIL_SENDER, [GMAIL_RECIPIENT], msg.encode("utf-8"))
          print(f"email sent -> {GMAIL_RECIPIENT}")
      def main() -> int:
          if not PROMPT_FILE.exists():
              print(f"::error::Prompt file missing: {PROMPT_FILE}")
              return 1
          prompt = PROMPT_FILE.read_text(encoding="utf-8")
          print(f"calling {MODEL}...")
          tables_md = call_llm(prompt)
          if not tables_md or "|" not in tables_md:
              print(f"::error::LLM returned no tables. First 500 chars:\n{tables_md[:500]}")
              return 2
          header = f"# Daily PM/PO Leads - {TODAY}\n\nGenerated by GitHub Actions (Plan B). OpenRouter model: `{MODEL}`.\n\n"
          archive_body = header + tables_md
          email_body   = header + tables_md
          LEADS_DIR.mkdir(parents=True, exist_ok=True)
          LEADS_FILE.write_text(archive_body, encoding="utf-8")
          print(f"wrote {LEADS_FILE} ({len(archive_body)} chars)")
          try:
              send_email(f"Daily PM/PO Leads - {TODAY}", email_body)
          except Exception as e:
              print(f"::error::Gmail send failed: {e}")
              return 3
          return 0
      if __name__ == "__main__":
          sys.exit(main())
